SELECT DEPARTMENT_ID, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10;

SELECT DEPARTMENT_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 2000;

SELECT DEPARTMENT_ID, FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID = 'AD_VP';

SELECT DEPARTMENT_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 2000;

SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE = '04/02/17';

SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_ID <> 30;

--24번 최대,최소값 구하기
SELECT JOB_ID, MIN_SALARY, MAX_SALARY
FROM JOBS
WHERE JOB_ID='IT_PROG';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = 'Steven';

SELECT DEPARTMENT_ID, JOB_ID, FIRST_NAME
FROM EMPLOYEES
WHERE JOB_ID = 'AD_VP';

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE SALARY >= 2000 AND DEPARTMENT_ID=30;

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE JOB_ID='ST_MAN' AND HIRE_DATE >= '04-01-01';

SELECT DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS
WHERE NOT LOCATION_ID=1700;

SELECT FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY >= 5000 AND JOB_ID='IT_PROG';

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID LIKE '13%'; 

SELECT FIRST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID LIKE '20%';

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%';

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 1000 AND 2500; 

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '05-10-01' AND '05-10-31';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME BETWEEN 'H%' AND 'J%';

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(10,30);

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(166,129);

SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IN(100,103);

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN('SA_MAN','SA_REP');

SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, SALARY DESC; -- 숫자값은 오름, 내림차순 // 문자값은 같은 것끼리 또는 오름, 내림차순

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
ORDER BY JOB_ID, SALARY;

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, JOB_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, JOB_ID, SALARY;

















