SELECT LOWER(FIRST_NAME) 사원이름
FROM EMPLOYEES;

SELECT LOWER(FIRST_NAME) 사원이름,
LOWER(JOB_ID) 사원직군
FROM EMPLOYEES;

SELECT UPPER(FIRST_NAME) 사원이름
FROM EMPLOYEES;

SELECT UPPER(FIRST_NAME) 사원이름,
UPPER(JOB_ID) 사원직군
FROM EMPLOYEES;

SELECT INITCAP(FIRST_NAME) 사원이름
FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME,JOB_ID) 사원연결
FROM EMPLOYEES;

SELECT FIRST_NAME, SUBSTR(FIRST_NAME,1,2) 문자열추출
FROM EMPLOYEES;

SELECT FIRST_NAME, JOB_ID, SUBSTR(JOB_ID,4,2) 문자열추출
FROM EMPLOYEES;

SELECT FIRST_NAME, PHONE_NUMBER, SUBSTR(PHONE_NUMBER, 1, 3) 지역번호
FROM EMPLOYEES;

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%n';

SELECT FIRST_NAME, LENGTH(FIRST_NAME) 문자길이
FROM EMPLOYEES;

SELECT FIRST_NAME, JOB_ID, LENGTH(FIRST_NAME) 문자길이
FROM EMPLOYEES;

SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a') "a의 위치"
FROM EMPLOYEES;

SELECT JOB_ID, INSTR(JOB_ID, 'A') "A의 위치"
FROM EMPLOYEES;

SELECT RPAD(FIRST_NAME,15,'&') 패턴
FROM EMPLOYEES;

SELECT LPAD(JOB_ID,20,'%') 패턴
FROM EMPLOYEES;

SELECT ROUND(3456.79, 2)
FROM DUAL;

SELECT TRUNC(3456.789, 0)
FROM DUAL;

SELECT EMPLOYEE_ID, SALARY, MOD(SALARY, 1000) 나머지
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, HIRE_DATE+100 "100 후"
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, TRUNC(SYSDATE - HIRE_DATE) "근무일자"
FROM EMPLOYEES;

SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE,3) 삼개월후날짜
FROM EMPLOYEES;

SELECT HIRE_DATE, NEXT_DAY(HIRE_DATE, '토') 토요일날짜
FROM EMPLOYEES;

SELECT HIRE_DATE, LAST_DAY(HIRE_DATE) 마지막날짜
FROM EMPLOYEES;

SELECT HIRE_DATE, ROUND(HIRE_DATE, 'YY') 반올림
FROM EMPLOYEES;

SELECT HIRE_DATE, TRUNC(HIRE_DATE, 'YY') 버림
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, NVL(TO_CHAR(MANAGER_ID),'CEO') 관리자번호 -- NVL안에 두 데이터는 서로 자료형이 같아야됨
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT, (SALARY+NVL(COMMISSION_PCT,0))*12 연봉계산
FROM EMPLOYEES;
--77번
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, TO_CHAR(HIRE_DATE,'YYYY-MM-DD') 입사년월일,
CONCAT(TO_CHAR(HIRE_DATE,'YYYY'),' 년'), TO_CHAR(SALARY, '$99,999'), NVL(COMMISSION_PCT, 0) 
FROM EMPLOYEES;

--4/10

SELECT MAX(FIRST_NAME) 최대값, MIN(FIRST_NAME) 최소값
FROM EMPLOYEES;

SELECT MAX(HIRE_DATE) 최대값, MIN(HIRE_DATE) 최소값
FROM EMPLOYEES;

SELECT COUNT(MANAGER_ID)
FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID)
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) 부서인원수
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 1;

SELECT MANAGER_ID, COUNT(MANAGER_ID) 관리인원수
FROM EMPLOYEES
GROUP BY MANAGER_ID
ORDER BY 1;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 1;

--?
SELECT JOB_ID, SUM(SALARY) 직군연봉합
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY 1;

SELECT JOB_ID, ROUND(AVG(SALARY)) 직군평균연봉
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY 1;

SELECT DEPARTMENT_ID, JOB_ID, MAX(HIRE_DATE), MIN(HIRE_DATE)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY 1;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) BETWEEN 7000 AND 20000
ORDER BY 1;
