DESC STUDENT;
DESC SUBJECT;
DESC ENROL;

SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT STU_NO, STU_NAME, STU_GENDER
FROM STUDENT;
--8
SELECT * FROM STUDENT;

SELECT STU_NO, STU_NAME, STU_GRADE, STU_CLASS
FROM STUDENT;

SELECT SUB_NAME, SUB_PROF
FROM SUBJECT;

SELECT STU_NO, STU_NAME, STU_HEIGHT, STU_WEIGHT
FROM STUDENT;

SELECT DISTINCT STU_DEPT
FROM STUDENT;

SELECT DISTINCT STU_DEPT, STU_CLASS
FROM STUDENT;

SELECT STU_WEIGHT+5
FROM STUDENT;

SELECT STU_WEIGHT-5
FROM STUDENT;

SELECT STU_NO 학번, STU_NAME 이름
FROM STUDENT;

--21
SELECT SUB_NO "순번" ,STU_NO "학번",ENR_GRADE "점수"
FROM ENROL;

SELECT SUB_NAME 과목이름 , SUB_PROF 교수명
FROM SUBJECT;

SELECT CONCAT(STU_DEPT,STU_NAME) AS "학과명+이름"
FROM STUDENT;

SELECT STU_DEPT || '과 ' || STU_NAME || '입니다.' AS 학과및이름
FROM STUDENT;

SELECT STU_NAME
FROM STUDENT
WHERE STU_DEPT='기계';

SELECT STU_NAME
FROM STUDENT
WHERE STU_DEPT='전기전자';

SELECT STU_NAME
FROM STUDENT
WHERE STU_HEIGHT >= 170;

--데이터 앞에 L들어가는거 뭐였더라?

SELECT STU_NAME
FROM STUDENT
WHERE STU_WEIGHT <= 65;

SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT='기계';

SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT='전기전자';

SELECT STU_GENDER
FROM STUDENT;
--33
SELECT STU_NAME
FROM STUDENT
WHERE STU_GENDER='M';

SELECT STU_NAME
FROM STUDENT
WHERE STU_GENDER='F';

SELECT STU_DEPT, STU_NAME
FROM STUDENT
WHERE NOT STU_DEPT='전기전자';

SELECT STU_DEPT, STU_NAME
FROM STUDENT
WHERE NOT STU_DEPT='기계';

SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT STU_NO
FROM ENROL
WHERE ENR_GRADE >= 80;

SELECT *
FROM STUDENT
WHERE STU_NAME='김인중';

SELECT *
FROM STUDENT
WHERE STU_DEPT='기계' AND STU_GRADE=2;

SELECT STU_NAME
FROM STUDENT
WHERE STU_GENDER='F' AND STU_WEIGHT <= 60;

SELECT STU_NAME
FROM STUDENT
WHERE NOT STU_DEPT = '컴퓨터정보';

SELECT SUB_NAME
FROM SUBJECT
WHERE NOT SUB_DEPT = '기계공작법';

SELECT STU_NAME
FROM STUDENT
WHERE STU_DEPT='컴퓨터정보' AND STU_GRADE=2 AND STU_CLASS='A';

SELECT * FROM STUDENT;

SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_HEIGHT BETWEEN 160 AND 170;

SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_NO LIKE '2013%';

SELECT *
FROM STUDENT
WHERE STU_GRADE IN(1,3);

SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_NAME LIKE '김%';
--49?
SELECT *
FROM STUDENT
WHERE STU_NO LIKE '____20_%'; --%가 뒤에 하나는 들어가야함, %하나가 1글자로 인식 나머지는 _로대체

SELECT *
FROM STUDENT
WHERE STU_NO LIKE '____20__'; 

--49
SELECT *
FROM STUDENT
WHERE SUBSTR(STU_NO,5,2) = '20';

SELECT *
FROM STUDENT
WHERE STU_NO LIKE '%8%';

SELECT STU_NAME
FROM STUDENT
WHERE STU_NAME LIKE '%옥%';

SELECT STU_NAME
FROM STUDENT
WHERE STU_HEIGHT IS NULL;

SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL;

SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT='컴퓨터정보' OR STU_DEPT='기계';

SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_GENDER='M' OR STU_GRADE=1;

SELECT STU_NO, STU_NAME
FROM STUDENT
ORDER BY STU_NO;

SELECT STU_NO, STU_NAME
FROM STUDENT
ORDER BY STU_NAME;

SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
ORDER BY STU_NAME;

SELECT *
FROM STUDENT
ORDER BY STU_DEPT, STU_GRADE DESC;

SELECT STU_NAME, STU_DEPT, STU_GRADE
FROM STUDENT
GROUP BY STU_NAME, STU_DEPT, STU_GRADE
ORDER BY STU_DEPT, STU_GRADE DESC;

SELECT LOWER(STU_GENDER)
FROM STUDENT;

SELECT UPPER(STU_GENDER)
FROM STUDENT;

SELECT CONCAT(STU_DEPT,STU_NAME)
FROM STUDENT;

SELECT CONCAT(STU_DEPT,'과'),
        CONCAT(STU_GRADE,'학년'),
        CONCAT(STU_NAME,'입니다.')
FROM STUDENT;

SELECT STU_DEPT || '과' || STU_GRADE || '학년' || STU_NAME || '입니다.' AS 학생정보
FROM STUDENT;

SELECT STU_NAME, SUBSTR(STU_NAME,1,2)
FROM STUDENT;

SELECT STU_NAME, STU_DEPT, SUBSTR(STU_DEPT,2,1)
FROM STUDENT;

--68
SELECT STU_NAME, LENGTH(STU_NAME) 이름길이
FROM STUDENT;

SELECT STU_DEPT, LENGTH(STU_DEPT) 학과명길이
FROM STUDENT;

SELECT STU_NAME, INSTR(STU_NAME,'김') "'김'몇번쨰있니"
FROM STUDENT;

SELECT STU_DEPT, INSTR(STU_DEPT,'기') "'기'몇번쨰있니"
FROM STUDENT;

SELECT RPAD(STU_NAME,15,'&')
FROM STUDENT;

SELECT LPAD(STU_DEPT,20,'%')
FROM STUDENT;

SELECT STU_DEPT, STU_NAME, ROUND(STU_HEIGHT)
FROM STUDENT;

SELECT STU_NO, STU_NAME, TRUNC(STU_HEIGHT,1)
FROM STUDENT;

SELECT MOD(STU_WEIGHT,30)
FROM STUDENT;

--77
SELECT STU_HEIGHT, NVL(TO_CHAR(STU_HEIGHT),'미기록')
FROM STUDENT;

SELECT STU_NO, STU_NAME, stu_height + stu_weight
FROM STUDENT;

SELECT STU_NO, STU_NAME, STU_HEIGHT - STU_WEIGHT
FROM STUDENT;

SELECT STU_NO, STU_NAME, NVL(TO_CHAR(STU_HEIGHT),'입력요망')
FROM STUDENT;

--키 가장큰 사람이 누군지?
SELECT MAX(STU_HEIGHT)
FROM STUDENT;

SELECT MIN(STU_HEIGHT)
FROM STUDENT;

SELECT MIN(STU_WEIGHT)
FROM STUDENT;

SELECT MAX(STU_NAME), MIN(STU_NAME)
FROM STUDENT;

SELECT MAX(STU_WEIGHT), MIN(STU_WEIGHT), MAX(STU_HEIGHT), MIN(STU_HEIGHT)
FROM STUDENT;

SELECT MAX(STU_NO), MIN(STU_NO)
FROM STUDENT;

SELECT COUNT(DISTINCT STU_DEPT)
FROM STUDENT;

SELECT COUNT(DISTINCT STU_NAME)
FROM STUDENT;

SELECT COUNT(*)
FROM ENROL;

SELECT STU_DEPT, COUNT(STU_DEPT) 학과별학생수
FROM STUDENT
GROUP BY STU_DEPT;

SELECT STU_DEPT, COUNT(STU_DEPT) 학과별학생수
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY 2 DESC, 1 DESC;

SELECT STU_GRADE, COUNT(STU_GRADE)
FROM STUDENT
GROUP BY STU_GRADE;

SELECT STU_GRADE, COUNT(STU_GRADE)
FROM STUDENT
GROUP BY STU_GRADE
ORDER BY 2 DESC;

SELECT STU_DEPT, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT STU_WEIGHT, STDDEV(STU_WEIGHT)
FROM STUDENT
GROUP BY STU_WEIGHT;

SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
ORDER BY STU_DEPT;

SELECT STU_DEPT, STU_GRADE, AVG(STU_WEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
ORDER BY STU_DEPT;

SELECT STU_DEPT, STU_GRADE, MAX(STU_NO), MIN(STU_NO)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
ORDER BY STU_DEPT;

--100
SELECT STU_DEPT, COUNT(STU_DEPT)
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY 2 DESC, 1 DESC;

SELECT STU_DEPT, STU_GRADE, AVG(STU_WEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
ORDER BY 3 DESC;

SELECT STU_DEPT, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY 2 DESC;

--104
SELECT STU_DEPT, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY 2;





