--1
SELECT *
FROM STUDENT JOIN ENROL USING(STU_NO); --중복 제거하고 조인
--2 ?
SELECT *
FROM STUDENT S, ENROL E, GRADE G
WHERE S.STU_NO = E.STU_NO
AND E.ENR_GRADE BETWEEN SCORE_FROM AND SOCRE_TO; --이것도 조인
--3
SELECT  S.STU_NO,
        STU_NAME,
        STU_GRADE,
        ENR_GRADE,
        SUB_NAME,
        SUB_PROF,
        SCORE_NAME
FROM STUDENT S, ENROL E, GRADE G, SUBJECT SUB
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO
AND ENR_GRADE BETWEEN SCORE_FROM AND SOCRE_TO;
--3
SELECT  STU_NAME,
        ENR_GRADE
FROM STUDENT S, ENROL E
WHERE S.STU_NO = E.STU_NO
AND ENR_GRADE IN (SELECT ENR_GRADE FROM ENROL WHERE ENR_GRADE >= 70);
--4
SELECT STU_NAME,
        ENR_GRADE
FROM STUDENT S, ENROL E
WHERE S.STU_NO = E.STU_NO
AND ENR_GRADE >= 70;
--5
SELECT STU_NAME
FROM STUDENT S, (SELECT ENR_GRADE, STU_NO FROM ENROL) E
WHERE E.STU_NO = E.STU_NO
AND ENR_GRADE >= 70;

--6
SELECT *
FROM STUDENT S, ENROL E
WHERE S.STU_NO = E.STU_NO
AND ENR_GRADE <= 70;

--7
SELECT  S.STU_NO,
        STU_NAME,
        STU_DEPT,
        ENR_GRADE
FROM STUDENT S, (SELECT ENR_GRADE, STU_NO FROM ENROL) E
WHERE S.STU_NO = E.STU_NO
AND E.ENR_GRADE <= 70;

--8
SELECT  SUB.SUB_NAME,
        SUB.SUB_PROF,
        STU_NAME
FROM STUDENT S, ENROL E, SUBJECT SUB 
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO
AND STU_NAME = '김인중';

--9
SELECT  SUB.SUB_NAME,
        SUB.SUB_PROF,
        STU_NAME
FROM STUDENT S, ENROL E, SUBJECT SUB 
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO
AND STU_NAME = (SELECT STU_NAME FROM STUDENT WHERE STU_NAME='김인중');

--10
SELECT  SUB.SUB_NAME,
        SUB.SUB_PROF,
        STU_NAME
FROM 
(SELECT STU_NAME,STU_NO FROM STUDENT WHERE STU_NAME='김인중') S,
(SELECT STU_NO, SUB_NO FROM ENROL) E,
(SELECT SUB_NO, SUB_NAME, SUB_PROF FROM SUBJECT) SUB
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO
AND STU_NAME = S.STU_NAME;

--11
SELECT STU_NAME,
        SUB_NAME,
        SUB_PROF
FROM STUDENT S, ENROL E,
(SELECT SUB_NO, SUB_NAME, SUB_PROF FROM SUBJECT WHERE SUB_PROF='강종영') SUB
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO
AND SUB_PROF = SUB.SUB_PROF;

--12
SELECT STU_NAME,
        SUB_NAME,
        SUB_PROF
FROM STUDENT S, ENROL E, SUBJECT SUB
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO
AND SUB_PROF = (SELECT SUB_PROF FROM SUBJECT WHERE SUB_PROF='강종영');

--13
SELECT STU_NAME,
        S.STU_NO, --STU.NO가 어디에 있는지 명시해줄 것
        SUB_NAME
FROM STUDENT S, ENROL E,
(SELECT SUB_NO, SUB_PROF, SUB_NAME FROM SUBJECT WHERE SUB_PROF='강종영') SUB
WHERE S.STU_NO = E.STU_NO
AND E.SUB_NO = SUB.SUB_NO;

--14
SELECT 

